# Generated by Django 3.1 on 2022-01-20 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220118_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=111)),
                ('address_line2', models.CharField(blank=True, max_length=111)),
                ('profile_picture', models.ImageField(blank=True, upload_to='user_profile')),
                ('city', models.CharField(blank=True, max_length=55)),
                ('state', models.CharField(blank=True, max_length=55)),
                ('country', models.CharField(blank=True, max_length=55)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
