# Generated by Django 3.2 on 2022-03-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220321_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='useprofile/images.jpg', upload_to='user_profile'),
        ),
    ]
