# Generated by Django 3.2 on 2022-03-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user_profile/images.jpg', upload_to='user_profile'),
        ),
    ]
